spring:
  main:
    lazy-initialization: true
  cloud:
    gateway:
      httpclient:
        pool:
          type: fixed
          max-connections: 30
          max-idle-time: 15s
          max-life-time: 60s
        connect-timeout: 3000
        response-timeout: 5s

management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 0.1

logging:
  level:
    root: WARN

server:
  shutdown: graceful
  http2:
    enabled: true
