spring.application.name=AiChatService
server.port=4002

# OpenAI Configuration (Requires key in environment variable: SPRING_AI_OPENAI_API_KEY)
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o

# gRPC Client Configuration
grpc.client.patient-service.address=static://${PATIENT_SERVICE_GRPC_URI:localhost:9091}
grpc.client.patient-service.negotiation-type=plaintext

# Actuator
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always

# Logging
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
