apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
      version: v2
  template:
    metadata:
      labels:
        app: patient-service
        version: v2
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: patient-service
          image: patient-service:v2 # Representing a new version
          ports:
            - containerPort: 4000
            - containerPort: 9091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_VAULT_ENABLED
              value: "false"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://patient-db:5432/patientdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 4000
            failureThreshold: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 4000
            initialDelaySeconds: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 4000
            initialDelaySeconds: 1
            periodSeconds: 10
