apiVersion: v1
kind: Service
metadata:
  name: patient-db
spec:
  ports:
    - port: 5432
  selector:
    app: patient-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-db
  template:
    metadata:
      labels:
        app: patient-db
    spec:
      containers:
        - name: db
          image: postgres:18-alpine
          env:
            - name: POSTGRES_DB
              value: patientdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
