spring.main.lazy-initialization=true
management.endpoint.health.probes.enabled=true
management.tracing.sampling.probability=0.1
logging.level.root=warn
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
